name: Monitoramento de Logs

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/10 * * * *'  # Executa a cada 10 minutos
  workflow_dispatch:  # Permite executar manualmente

jobs:
  monitoramento:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositório
      uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Executar script de monitoramento
      run: python monitor_log.py

    - name: Commit se CSV for gerado
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"

        if [ -f eventos_seguranca.csv ]; then
          git add eventos_seguranca.csv
          git commit -m "Atualizando eventos detectados [bot]" || echo "Nada para commitar"

          # Configura a URL remota com token para autenticar o push
          # git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/LKLuks/prova-final.git
          git push https://LKLuks:${GH_TOKEN}@github.com/LKLuks/prova-final.git main
        else
          echo "⚠️ Arquivo eventos_seguranca.csv não foi encontrado, nada a fazer."
        fi


