name: Monitoramento de Logs

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/10 * * * *'  # Executa a cada 10 minutos
  workflow_dispatch:  # Permite executar manualmente

jobs:
  monitoramento:
    runs-on: ubuntu-latest 
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests**

    steps:
    - name: Checkout repositório
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Executar script de monitoramento
      run: python monitor_log.py

    - name: Commit se CSV for gerado
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        if [ -f eventos_seguranca.csv ]; then
          git add eventos_seguranca.csv
          git commit -m "Atualizando eventos detectados [bot]" || echo "Nada para commitar"

          # Configura a URL remota com token para autenticar o push
          git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin main
        else
          echo "⚠️ Arquivo eventos_seguranca.csv não foi encontrado, nada a fazer."
        fi


