name: Monitoramento de Logs

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/10 * * * *'  # Executa a cada 10 minutos
  workflow_dispatch:  # Permite executar manualmente

jobs:
  monitoramento:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositório
      uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Executar script de monitoramento
      run: python monitor_log.py

    - name: Commit se CSV for gerado
      run: |
        git config --local user.name "github-actions"

        if [ -f eventos_seguranca.csv ]; then
          git add eventos_seguranca.csv
          git commit -m "Atualizando eventos detectados [bot]" || echo "Nada para commitar"
          git push
        else
          echo "⚠️ Arquivo eventos_seguranca.csv não foi encontrado, nada a fazer."
        fi

