name: Monitoramento de Logs

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/10 * * * *'  # Executa a cada 10 minutos

jobs:
  monitoramento:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Executar script de monitoramento
      run: |
        python monitor_log.py

    - name: Commit se CSV for gerado
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        if [ -f eventos_seguranca.csv ]; then
          git add eventos_seguranca.csv
          git commit -m "Atualizando eventos detectados [bot]" || echo "Nada para commitar"
          git push
        else
          echo "⚠️ Arquivo eventos_seguranca.csv não foi encontrado, nada a fazer."
        fi
